CREATE USER SMC_USER IDENTIFIED BY SMC_USER; // SMC_USER라는 이름의 유저를 생성

GRANT CREATE SESSION TO SMC_USER; // SMC_USER라는 이름의 유저가 데이터베이스의 접속할수있는권한을준다
GRANT CREATE TABLE TO SMC_USER; // SMC_USER라는 이름의 유저가 테이블 생성을 할수 있는 권한을 주는 구문이다

SELECT 1 FROM DUAL; // SMC_USER라는 이름의 유저가 권한이 제대로 주어졌는지 확인하는 구문

CREATE TABLE A (A varchar2(10));

CREATE TABLESPACE smc
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE/smc.DBF'
SIZE 2048M
AUTOEXTEND ON
NEXT 4M MAXSIZE UNLIMITED
LOGGING PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;

ALTER USER SMC_USER
IDENTIFIED BY SMC_USER
DEFAULT TABLESPACE smc
quota UNLIMITED on smc;

INSERT INTO A(A) VALUES('ABCTEST');

DROP TABLE A;